import type * as React from 'react';
export type ACI = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
export type Linetype = 'continuous' | 'dashed' | 'hidden' | 'center' | 'phantom' | 'dot' | 'dashdot';
export type HatchPattern = 'ANSI31' | 'ANSI32' | 'ANSI37' | 'BRICK' | 'NET' | 'DOTS' | 'EARTH' | 'SOLID';
export type WorkspaceProps = { width?: number; height?: number; status?: StatusLineProps; menuBar?: MenuBarProps; pulldown?: PulldownMenuProps; screenMenu?: ScreenMenuProps; command?: CommandLineProps; viewport?: Partial<ViewportProps>; children?: React.ReactNode };
export declare function Workspace(props: WorkspaceProps): React.ReactElement;
export type TextModeMenuProps = { header?: string[]; heading?: string; options: Array<{ n: number; label: string } | ''>; prompt?: string; value?: string; cursor?: boolean };
export declare function TextModeMenu(props: TextModeMenuProps): React.ReactElement;
export type StatusLineProps = { layer?: string; layerColor?: ACI; modes?: string[]; coords?: string };
export declare function StatusLine(props: StatusLineProps): React.ReactElement;
export type MenuBarProps = { items: string[]; active?: number };
export declare function MenuBar(props: MenuBarProps): React.ReactElement;
export type PulldownMenuProps = { items: Array<string | '-' | { label: string; key?: string; checked?: boolean; disabled?: boolean }>; active?: number };
export declare function PulldownMenu(props: PulldownMenuProps): React.ReactElement;
export type ScreenMenuProps = { title?: string; items: Array<string | { label: string; dim?: boolean }>; active?: number; onSelect?: (item: { label: string }, index: number) => void; footer?: string[] };
export declare function ScreenMenu(props: ScreenMenuProps): React.ReactElement;
export type CommandLineProps = { history?: string[]; prompt?: string; value?: string; rows?: number; cursor?: boolean };
export declare function CommandLine(props: CommandLineProps): React.ReactElement;
export type DialogProps = { title: string; width?: number; actions?: React.ReactNode; children?: React.ReactNode };
export declare function Dialog(props: DialogProps): React.ReactElement;
export type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & { isDefault?: boolean; focus?: boolean; pressed?: boolean };
export declare function Button(props: ButtonProps): React.ReactElement;
export type EditBoxProps = { label?: string; value?: string; cols?: number; onChange?: React.ChangeEventHandler<HTMLInputElement> };
export declare function EditBox(props: EditBoxProps): React.ReactElement;
export type ToggleProps = { label: string; checked?: boolean; onChange?: (next: boolean) => void };
export declare function Toggle(props: ToggleProps): React.ReactElement;
export type ListBoxProps = { items: string[]; selected?: number; rows?: number; width?: number };
export declare function ListBox(props: ListBoxProps): React.ReactElement;
export type ColorSwatchProps = { aci?: ACI; size?: number; label?: string | false };
export declare function ColorSwatch(props: ColorSwatchProps): React.ReactElement;
export type LayerTableProps = { layers: Array<{ name: string; color: ACI; linetype?: Linetype; on?: boolean; frozen?: boolean }>; selected?: number; width?: number };
export declare function LayerTable(props: LayerTableProps): React.ReactElement;
export type IconMenuProps = { title: string; columns?: number; active?: number; tiles: Array<{ pattern?: HatchPattern; aci?: ACI; label?: string; render?: () => React.ReactNode }> };
export declare function IconMenu(props: IconMenuProps): React.ReactElement;
export type HatchSwatchProps = { pattern?: HatchPattern; aci?: ACI; width?: number; height?: number };
export declare function HatchSwatch(props: HatchSwatchProps): React.ReactElement;
export type ViewportProps = { width?: number; height?: number; grid?: boolean; gridPitch?: number; crosshair?: { x: number; y: number }; pickbox?: boolean; ucs?: boolean; label?: string; children?: React.ReactNode };
export declare function Viewport(props: ViewportProps): React.ReactElement;
export type LineProps = { x1: number; y1: number; x2: number; y2: number; aci?: ACI; linetype?: Linetype; weight?: number };
export declare function Line(props: LineProps): React.ReactElement;
export type CircleProps = { cx: number; cy: number; r: number; aci?: ACI; linetype?: Linetype; weight?: number };
export declare function Circle(props: CircleProps): React.ReactElement;
export type LinearDimProps = { x1: number; y1: number; x2: number; y2: number; direction?: 'horizontal' | 'vertical'; offset?: number; text?: string; unit?: number; aci?: ACI; size?: number };
export declare function LinearDim(props: LinearDimProps): React.ReactElement;
export type DrawingTextProps = { x: number; y: number; size?: number; aci?: ACI; anchor?: 'start' | 'middle' | 'end'; rotate?: number; duplex?: boolean; children?: React.ReactNode };
export declare function DrawingText(props: DrawingTextProps): React.ReactElement;
export type TitleBlockProps = { title: string; company?: string; number?: string; rev?: string; scale?: string; sheet?: string; drawn?: string; date?: string; units?: string; width?: number };
export declare function TitleBlock(props: TitleBlockProps): React.ReactElement;
declare global { interface Window { R10: { Workspace: typeof Workspace; TextModeMenu: typeof TextModeMenu; StatusLine: typeof StatusLine; MenuBar: typeof MenuBar; PulldownMenu: typeof PulldownMenu; ScreenMenu: typeof ScreenMenu; CommandLine: typeof CommandLine; Dialog: typeof Dialog; Button: typeof Button; EditBox: typeof EditBox; Toggle: typeof Toggle; ListBox: typeof ListBox; ColorSwatch: typeof ColorSwatch; LayerTable: typeof LayerTable; IconMenu: typeof IconMenu; HatchSwatch: typeof HatchSwatch; Viewport: typeof Viewport; Line: typeof Line; Circle: typeof Circle; LinearDim: typeof LinearDim; DrawingText: typeof DrawingText; TitleBlock: typeof TitleBlock; HATCH_PATTERNS: HatchPattern[] } } }
